// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPokemonByID(arg1) {
  return window['go']['app']['App']['GetPokemonByID'](arg1);
}

export function GetRandomPokemon() {
  return window['go']['app']['App']['GetRandomPokemon']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}
