// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetPokemonByID(arg1:number):Promise<models.Pokemon>;

export function GetRandomPokemon():Promise<models.Pokemon>;

export function Greet(arg1:string):Promise<string>;
